-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 16:46:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mall_item
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mall_item
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mall_item` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `mall_item` ;

-- -----------------------------------------------------
-- Table `mall_item`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mall_item`.`category` ;

CREATE TABLE IF NOT EXISTS `mall_item`.`category` (
  `cate_code` VARCHAR(50) NOT NULL,
  `cate_name` VARCHAR(255) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_at` DATETIME NULL,
  PRIMARY KEY (`cate_code`),
  UNIQUE INDEX `name_UNIQUE` (`cate_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mall_item`.`item_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mall_item`.`item_master` ;

CREATE TABLE IF NOT EXISTS `mall_item`.`item_master` (
  `id` VARCHAR(50) NOT NULL,
  `item_name` VARCHAR(100) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_at` DATETIME NULL,
  `cate_code` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`item_name` ASC) VISIBLE,
  INDEX `FK_ITEM_MASTER_TO_CATEGORY_idx` (`cate_code` ASC) VISIBLE,
  CONSTRAINT `FK_ITEM_MASTER_TO_CATEGORY`
    FOREIGN KEY (`cate_code`)
    REFERENCES `mall_item`.`category` (`cate_code`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mall_item`.`item_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mall_item`.`item_option` ;

CREATE TABLE IF NOT EXISTS `mall_item`.`item_option` (
  `id` VARCHAR(50) NOT NULL,
  `option_name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL DEFAULT 0,
  `stock` INT NOT NULL DEFAULT 0,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_at` DATETIME NULL,
  `item_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `option_name_UNIQUE` (`option_name` ASC) VISIBLE,
  INDEX `FK_ITEM_OPTION_TO_ITEM_MASTER_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `FK_ITEM_OPTION_TO_ITEM_MASTER`
    FOREIGN KEY (`item_id`)
    REFERENCES `mall_item`.`item_master` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
